services:
  server:
    build: .
    container_name: Withlive_backend
    ports:
      - "20000:20000"

  privacy:
    image: nginx
    ports:
        - 20001:80
    volumes:
        - ./privacy:/usr/share/nginx/html
    healthcheck:
        test: curl --fail http://localhost || exit 1
        interval: 60s
        retries: 5
        start_period: 20s
        timeout: 10s